name: build on ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Ready
        working-directory: ./easycontrol
        if: runner.os == 'Linux'
        run: |
          chmod +x *
          pwd
          ls -la
        # if: runner.os == 'Windows'
        # run: |
        #   dir /A

      - name: Write key
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        working-directory: ./easycontrol
        run: |
          echo buildWithGitSuffix=true >> local.properties
          echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo keyAlias='${{ secrets.ALIAS }}' >> local.properties
          echo keyPassword='${{ secrets.ALIAS_KEY_PASSWORD }}' >> local.properties
          echo fileDir=`pwd`/key.jks >> local.properties
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > key.jks
        # echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Validate key
        working-directory: ./easycontrol
        run: |
          keytool -list -keystore key.jks -storepass ${{ secrets.KEY_STORE_PASSWORD }} -alias ${{ secrets.ALIAS }} -storetype JKS
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'

      - name: Gradle prebuild
        working-directory: ./easycontrol
        run: |
          ./gradlew prebuild

      - name: Build Debug APK
        id: buildDebug
        working-directory: ./easycontrol
        run: |
          ./gradlew :server:copyRelease --stacktrace
          ./gradlew :app:assembleDebug --stacktrace
          echo "debugApkName=$(ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.apk)' '{print $5}')" >> $GITHUB_OUTPUT

      - name: Build Release APK
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        id: buildRelease
        working-directory: ./easycontrol
        run: |
          ./gradlew :app:assembleRelease --stacktrace
          echo "releaseApkName=$(ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $5}')" >> $GITHUB_OUTPUT

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildDebug.outputs.debugApkName }}-debug
          path: "easycontrol/app/build/outputs/apk/debug/*.apk"

      - name: Upload Release APK
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildRelease.outputs.releaseApkName }}-release
          path: "easycontrol/app/build/outputs/apk/release/*.apk"

      - name: Upload Release Mapping
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildRelease.outputs.releaseApkName }}-mapping
          path: "easycontrol/app/build/outputs/mapping/release"
